version: '3'

services:
  consumer:
    build:
      dockerfile: Dockerfile
      context: consumer/main/
    networks:
      - failover-net
    ports:
      - "8080:8080"
  producer:
      build:
        dockerfile: Dockerfile
        context: producer/main/
      environment:
        - CONSUMER_FRONTEND_SERVICE_HOST=consumer
        - CONSUMER_FRONTEND_SERVICE_PORT=8080
      networks:
        - failover-net

networks:
  failover-net:
