apiVersion: v1
kind: Service
metadata:
  name: consumer-frontend
  labels:
    app: consumer
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http-server
    nodePort: 30080
  selector:
    app: consumer
    tier: frontend

    # TODO only one consumer is being fed with data. It may not necessarily be the one served when accessing the outside address.