apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consumer-worker
  labels:
    app: consumer
    tier: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
        tier: worker
    spec:
      containers:
      - name: consumer-worker
        image: hauptseminarss18_producer:latest
        imagePullPolicy: IfNotPresent
        #env:
          #- name: CONSUMER_HOST
          #  value: 192.168.99.101:30080